# Appendix
This sections includes a list of sources and references I used
while working on this project that were not provided within 
the course modules. 

While working on this project, I used ChatGPT to help me work through the
confusion I faced with aiven cloud database setup, questions on keys,
sql queries (i.e. pivot table-like functions), stored procedure syntax, and formatting issues for knitting. The link to my chat is below:
https://chatgpt.com/share/68a16326-ac30-800c-9336-6666733c9c2e

  1. R Factor Levels:
    a. https://www.geeksforgeeks.org/r-language/group-factor-levels-in-r/#
  2. SQL References:
    a. writing dynamic SQL queries:
       i. https://www.johnmackintosh.net/blog/2022-04-06-sql-schema-query/
    b. finding duplicate rows:
       i. https://www.atlassian.com/data/sql/how-to-find-duplicate-values-in-a-sql-table
       ii. https://www.geeksforgeeks.org/r-language/identify-and-remove-duplicate-data-in-r/#
    c. writing stored procedures
       i. used ChatGPT to ask questions about syntax and SQL functions
    d. sql functions:
       i. https://www.baeldung.com/sql/group-by-multiple-columns
  3. Pivot Table/Reshaping Functionality
    a. got the original idea from a google search and this source: 
       https://www.datacamp.com/tutorial/sql-pivot
    b. more research led me to reshape() function:
       i. https://libguides.princeton.edu/R-reshape
       ii. https://stats.oarc.ucla.edu/r/faq/how-can-i-reshape-my-data-in-r/
  4. Plots & Tables:
    a. kable:
       https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html
    b. setting axis limits: 
       https://www.geeksforgeeks.org/r-language/set-axis-limits-of-plot-in-r/
  
